FROM grafana/xk6:latest AS builder

RUN xk6 build \
  --output /tmp/k6 \
  --with github.com/LeonAdato/xk6-output-statsd

FROM grafana/k6:latest

COPY --from=builder /tmp/k6 /usr/bin/k6

ENTRYPOINT ["k6"]
